- name: Install PostgreSQL
  hosts: db_server
  tasks:
    # In order to use postgresql module below
    - name: Make sure depedency is installed
      pip:
        name: "{{ item }}"
        state: 'present'
      with_items:
        - psycopg2-binary
        - docker

    - name: Pull Docker Image
      community.docker.docker_image:
        name: postgres
        source: pull
      register: pull_result
      failed_when: pull_result['failed']

    - name: Create PG Container
      community.docker.docker_container:
        name: pg-container
        image: postgres:latest
        volumes:
          - "{{ mount_path }}:{{ pg_data }}"
        env:
          POSTGRES_PASSWORD: "{{ postgre_password }}"
          PGDATA: "{{ pg_data }}"
        ports:
          - "5432:5432"
        auto_remove: true

    # Container need some time to init
    - name: Wait for Check DB Status
      wait_for:
        timeout: 5

    - name: Check PGSQL exist
      postgresql_ping:
        login_host: localhost
        login_user: postgres
        login_password: "{{ postgre_password }}"
      register: check_result
      failed_when: not check_result['is_available']
